before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libzip-dev libopenal-dev

language: haskell

install: true

script:
  - cd src
  - cabal sandbox init
  - cabal install sfml-audio --extra-include-dirs=/usr/include/AL/
  - ./linuxCompile.sh
